# $adJ$

# Port in the public domain.

VERSION=1.1.4

DISTNAME=sivel-${VERSION}
HOMEPAGE=	http://sivel.sourceforge.net/

RUN_DEPENDS= lang/php/5.3 \
	www/pear \
	security/pear-Auth \
	databases/pear-DB \
	devel/pear-Date \
	www/pear-HTML-QuickForm \
	net/pear-Net-Socket \
	net/pear-Net-SMTP \
	mail/pear-Mail  \
	mail/pear-Mail-Mime  \
	www/pear-HTML-Common  \
	www/pear-HTML-Menu \
	www/pear-HTML-QuickForm-Controller \
	www/pear-HTML-Javascript \
	www/pear-HTML-CSS \
	databases/pear-DB-DataObject \
	www/pear-DB-DataObject-FormBuilder \
	devel/pear-Validate \
	databases/postgresql 


MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=sivel/}
EXTRACT_SUFX=	.tar.gz

.include <bsd.port.mk>
