# $adJ$

COMMENT=	Reconoce archivo de configuración de Apache

DISTNAME=	apacheconf-parser-0.0.1

CATEGORIES=	devel

HOMEPAGE=	http://github.com/vtamara/apacheconf-parser
MASTER_SITES =	https://github.com/vtamara/apacheconf-parser/raw/master/pkg/


# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	lang/ruby
FLAVOR =	ruby21

CONFIGURE_STYLE=ruby gem 

.include <bsd.port.mk>
