# adJ. Dominio Público de acuerdo a legislación colombiana. 2013. vtamara@pasosdeJesus.or

COMMENT=	"design of HTML tables easy, flexible, reusable and efficient"

REVISION=	1
DISTNAME=	HTML_Table-1.8.4
PKGNAME=	pear-${DISTNAME:S/_/-/}
CATEGORIES=	www devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir Támara Patiño <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
 
.include <bsd.port.mk>
