# $OpenBSD: Makefile,v 1.3 2007/03/22 22:48:04 robert Exp $

COMMENT=	"allows building of multipage forms with HTML_QuickForm"

DISTNAME=	HTML_QuickForm_Controller-1.0.10
REVISION=	1
PKGNAME=	pear-${DISTNAME:S/_/-/g}
CATEGORIES=	www devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir T?mara Pati?o <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
