
SUBDIR += books
SUBDIR += databases
SUBDIR += devel     
SUBDIR += education
SUBDIR += fonts
SUBDIR += misc
SUBDIR += security
SUBDIR += textproc
SUBDIR += www
SUBDIR += x11

.include <bsd.port.subdir.mk>
