
COMMENT=	"object interface to database tables"

DISTNAME=	DB_DataObject-1.11.2
REVISION=	1
PKGNAME=        pear-${DISTNAME:S/_/-/}
CATEGORIES=	databases 

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir T?mara Pati?o <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
