# $OpenBSD: Makefile,v 1.0 2020/09/27 07:49:00 vtamara Exp $

COMMENT=        Perl5 class for use with the SGMLS and NSGMLS parsers

MODULES=        cpan
PKG_ARCH=       *
VERSION=        1.1
DISTNAME=       SGMLSpm-${VERSION}
CATEGORIES=     textproc
CPAN_AUTHOR=    RAAB
MAINTAINER=     Vladimir Támara Patiño <vtamara@pasosdeJesus.org>

# Same as Perl
PERMIT_PACKAGE= Yes

.include <bsd.port.mk>
