#!/bin/sh
# Realiza algunos resumenes de bitacoras para ayudar a analizarlas
# Dominio público de acuerdo a legislación colombiana.
# vtamara@pasosdeJesus.org. 2013

if (test $USER != "root") then {
	echo "Ejecutar como root";
	exit 1;
} fi;

d=`date +%Y%m%d`
d="/var/adJ/auditabitacoras/$d"
rep="$d/auditabitacoras.txt"
echo "Auditando y enviando reporte a $rep" | tee $rep


mkdir -p $d |
cp -rf /var/log/* $d
gzip -fd $d/*gz
#mkdir -p $d/www
#cp -rf /var/www/logs/* $d/www
#gzip -fd $d/www/*gz

echo "Descomprimiendo" | tee -a $rep
ua=`ls $d/authlog* | sort -u | tail -n 1`
fini=`head -n 1 $ua | sed -e "s/^\([A-Za-z]* [0-9]* [0-9:]*\) .*/\1/g"`
ffin=`tail -n 1 /var/log/authlog | sed -e "s/^\([A-Za-z]* [0-9]* [0-9:]*\) .*/\1/g"`

echo "Acceso de usuarios entre $fini y $ffin" | tee -a $rep
/usr/local/adJ/revisaauthlog.pl $d/authlog* >>  $rep

echo "Correos enviados" | tee -a $rep
(cd $d; sudo grep "Sent" maillog* | grep -v " to=\"" | sed -e "s/.* to=\([^=]*\), [a-z]*=.*/\1/g"  | sort -u) >> $rep

echo "Examinando bitacoras de Apache" | tee -a $rep
for i in /var/www/logs/*access_log; do 
	echo "** Bitacora $i" | tee -a $rep;
	/usr/local/adJ/revisaapachelog.pl $i* >> $rep
done

