#!/bin/sh
# Instala o actualiza programas requeridos por un servidor de correo
# configurado:
#   sendmail con SASL y SMTP-AUT 
#   SpamAssasin y Procmail
#   IMAPS, POP3S
# Dominio público de acuerdo a legislación colombiana. 
# vtamara@pasosdeJesus.org. 2013

. /etc/varcorreo.sh

. /usr/local/adJ/rutinas.sh

if (test ! -d "/usr/src/gnu/usr.sbin/sendmail") then {
	die "Instale fuentes en /usr/src";
} fi;
echo "Instalando cyrus-sasl"
insacp cyrus-sasl-2.1.25p2

echo 'pwcheck_method: saslauthd' > /usr/local/lib/sasl2/Sendmail.conf 
mkdir -p /var/sasl2

grep saslauthd /etc/rc.conf.local > /dev/null 2>&1 
if (test "$?" != "0") then {
	cat >> /etc/rc.conf.local <<EOF
saslauthd_flags="-a getpwent"
EOF
} fi;


activarcs saslauthd
/etc/rc.d/saslauthd start

grep WANT_SMTPAUTH /etc/mk.conf > /dev/null 2>&1 
if (test "$?" != "0") then {
	echo 'WANT_SMTPAUTH=yes' >> /etc/mk.conf 
} fi;

if (test ! -d /etc/mail/certs) then {
	echo "Creando certificados";
	mkdir /etc/mail/certs
	openssl dsaparam 1024 -out dsa1024.pem
	openssl req -x509 -nodes -days 3650 -newkey dsa:dsa1024.pem \
	  -out /etc/mail/certs/mycert.pem -keyout /etc/mail/certs/mykey.pem
	ln -s /etc/mail/certs/mycert.pem /etc/mail/certs/CAcert.pem
	rm dsa1024.pem
	chmod -R go-rwx /etc/mail/certs
} fi;

if (test "$NOCOMPILA" != "1") then {
	echo "Compilando";
	cd /usr/src/gnu/usr.sbin/sendmail/
	sudo cvs -z3 update -Pd
	sudo make clean
	sudo make
	echo "Por instalar, ENTER para continuar"
	read
	sudo make install
} fi;

cd /usr/src/gnu/usr.sbin/sendmail/cf/cf
if (test ! -f "/usr/src/gnu/usr.sbin/sendmail/cf/cf/openbsd-proto-local.mc") then {
	echo "Por crear openbsd-proto-local.mc";
	cp openbsd-proto.mc openbsd-proto-local.mc
	echo "modificar openbsd-proto-local.mc e instalar";
	cd /usr/src/gnu/usr.sbin/sendmail/cf/cf
	cat > /tmp/s.sed <<EOF
s/dnl define..CERT_DIR/define(\`CERT_DIR/g;
s/dnl define(\`confCACERT_PATH', \`CERT_DIR')dnl/define(\`confCACERT_PATH', \`CERT_DIR')/g;
s/dnl define(\`confCACERT', \`CERT_DIR\/mycert.pem')dnl/define(\`confCACERT',\`CERT_DIR\/CAcert.pem')/g;
s/dnl define(\`confSERVER_CERT', \`CERT_DIR\/mycert.pem')dnl/define(\`confSERVER_CERT', \`CERT_DIR\/mycert.pem')/g;
s/dnl define(\`confSERVER_KEY', \`CERT_DIR\/mykey.pem')dnl/define(\`confSERVER_KEY',  \`CERT_DIR\/mykey.pem')/g;
s/dnl define(\`confCLIENT_CERT', \`CERT_DIR\/mycert.pem')dnl/define(\`confCLIENT_CERT', \`CERT_DIR\/mycert.pem')/g;
s/dnl define(\`confCLIENT_KEY', \`CERT_DIR\/mykey.pem')dnl/define(\`confCLIENT_KEY',  \`CERT_DIR\/mykey.pem')/g;
s/FEATURE(\`no_default_msa')dnl/&|define(\`confAUTH_MECHANISMS',\`PLAIN LOGIN CRAM-MD5 DIGEST-MD5')dnl|TRUST_AUTH_MECH(\`PLAIN LOGIN CRAM-MD5 DIGEST-MD5')dnl|dnl define(\`confAUTH_OPTIONS',\`p,y')dnl|define(\`confPRIVACY_FLAGS',\`authwarnings,goaway')dnl/g;
s/DAEMON_OPTIONS(\`Family=inet, Address=0.0.0.0, Port=587, Name=MSA, M=E')dnl/DAEMON_OPTIONS(\`Family=inet, Address=0.0.0.0, Port=465, Name=MTASSL, M=s')dnl/g;
s/DAEMON_OPTIONS(\`Family=inet6, Address=::, Port=587, Name=MSA6, M=O, M=E')dnl/DAEMON_OPTIONS(\`Family=inet6, Address=::, Port=465, Name=MTA6, M=s')dnl/g
EOF
	sed -f /tmp/s.sed  < openbsd-proto.mc | tr "|" "\n" > openbsd-proto-local.mc
} fi;

make openbsd-proto-local.cf
if (test -f openbsd-proto-local.cf) then {
	uop=".";
} else {
	uop="obj";
} fi;
ad=`pwd`
echo "Por instalar $ad/$uop/openbsd-proto-local.cf, ENTER para continuar"
read
install -c -o root -g wheel -m 644 "$uop/openbsd-proto-local.cf" /etc/mail/sendmail.cf

grep sendmail /etc/rc.conf.local > /dev/null 2>&1 
if (test "$?" != "0") then {
	echo "Agregando banderas en rc.conf.local"
	cat >> /etc/rc.conf.local <<EOF
sendmail_flags="-L sm-mta -C/etc/mail/sendmail.cf -bd -q30m"
EOF
} fi;

activarcs sendmail
if [ "\$?" != "0" -a X"\$sendmail_flags" != X"NO" ]; then
	echo -n ' sendmail';
	/usr/sbin/sendmail \${sendmail_flags}
fi
EOF


# IMAP

echo "Instalando lo necesario para IMAP, Enter para continuar"
read
insacp courier-authlib

activarcs courier_authdaemond

insacp courier-imap

grep "IMAPDSTART *= *YES" /etc/courier/imapd > /dev/null 2>&1
if (test "$?" != "0") then {
	echo "Configurando /etc/courier/imapd";
	cp /etc/courier/imapd /etc/courier/imapd.copia
	sed -e "s/IMAPDSTART=NO/IMAPDSTART=YES/g;s/MAILDIRPATH=Maildir/MAILDIRPATH=$Maildir/g" /etc/courier/imapd.copia > /etc/courier/imapd
	(cd /etc/ssl/private; cat server.key ../server.crt > imapd.pem)
} fi;

activarcs courier_imap_ssl

echo "Recuerde abrir puerto 993 de su cortafuegos"

echo "Agregando SpamAssassin y Procmail";
insacp p5-Mail-SpamAssassin

insacp procmail

activarcs spamassassin

#sudo pkg_add -r -D update roundcubemail

			
# Reiniciamos servicios
pkill sendmail
pkill authd

sh /etc/rc.local
