# $OpenBSD: Makefile,v 1.7 2013/03/11 10:50:24 espie Exp $

COMMENT=	validation class

DISTNAME=	Validate-0.8.5
CATEGORIES=	devel

MODULES=	www/pear

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
