
COMMENT=	"Generates HTML menus from multidimensional hashes"

DISTNAME=	HTML_Menu-2.1.4
PKGNAME=	pear-${DISTNAME:S/_/-/}
CATEGORIES=	www devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir Támara Patiño <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
