# $adJ$
# Porte de dominio publico de acuerdo a legislacion colombiana 
#

COMMENT=	"Documentación básica de adJ"
PNAME=basico_adJ

include Make.inc

BUILD_DEPENDS+=  lang/ghc lang/cabal-install #pandoc local

