     SUBDIR += AnimalesI
     SUBDIR += AprestamientoI
     SUBDIR += NombresCursiva
     SUBDIR += PlantasCursiva
     SUBDIR += asigna
     SUBDIR += repasa
     SUBDIR += sigue

.include <bsd.port.subdir.mk>
