     SUBDIR += Animales1
     SUBDIR += Aprestamiento1
     SUBDIR += NombresCursiva
     SUBDIR += PlantasCursiva
     SUBDIR += asigna
     SUBDIR += repasa
     SUBDIR += sigue

.include <bsd.port.subdir.mk>
