# adJ. vtamara@pasosdeJesus.org Dominio Público. 2013 

COMMENT=	"build HTML_QuickForm objects from a DB_DataObject"

DISTNAME=	DB_DataObject_FormBuilder-1.0.2
PKGNAME=	pear-${DISTNAME:S/_/-/g}
REVISION= 	1
CATEGORIES=	www devel pear database

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir Támara Patiño <vtamara@pasosdeJesus.org>
MODULES=	www/pear

RUN_DEPENDS=	databases/pear-DB-DataObject

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
