
SUBDIR += pear-HTML-Menu
SUBDIR += pear-DB-DataObject-FormBuilder          
SUBDIR += pear-HTML-QuickForm
SUBDIR += pear-HTML-CSS                           
SUBDIR += pear-HTML-QuickForm-Controller
SUBDIR += pear-HTML-Common                        
SUBDIR += pear-HTML-Table
SUBDIR += pear-HTML-Javascript


.include <bsd.port.subdir.mk>
