# $adJ$
# Porte de dominio publico de acuerdo a legislacion colombiana 
#

COMMENT=	"Documentación de adJ como Servidor y Cortafuegos"
PNAME=servidor_adJ
EXTRACT_SUFX=.tar.gz

include ../basico_adJ/Make.inc
