# $OpenBSD: Makefile,v 1.3 2007/03/22 22:48:04 robert Exp $

COMMENT=	"class for generating CSS declarations"

REVISION=	1
DISTNAME=	HTML_CSS-1.5.4
PKGNAME=	pear-${DISTNAME:S/_/-/}
CATEGORIES=	www devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir Támara Patiño <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
