# $OpenBSD: Makefile,v 1.3 2007/03/22 22:48:04 robert Exp $

COMMENT=	"Provides an interface for creating simple JS scripts"

DISTNAME=	HTML_Javascript-1.1.2
PKGNAME=	pear-${DISTNAME:S/_/-/}
CATEGORIES=	www devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Vladimir Támara Patiño <vtamara@pasosdeJesus.org>
MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
